// File: postgres.go

package grpop

import (
	"context"
	_ "embed"
	"errors"
	"fmt"
	"math"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/gourdian25/grpop/internal/postgresdb"
)

// pgTimestamptz and pgTime convert between time.Time and pgtype.Timestamptz
// — shared by dlq.postgres.go's row<->domain mapping.
func pgTimestamptz(t time.Time) pgtype.Timestamptz {
	return pgtype.Timestamptz{Time: t, Valid: !t.IsZero()}
}

func pgTime(t pgtype.Timestamptz) time.Time {
	if !t.Valid {
		return time.Time{}
	}
	return t.Time.UTC()
}

// pgInt32 converts a caller-supplied int (e.g. a MaxRetries config value or
// a ClaimRetryableEvents limit) to the int32 every generated query param
// expects, clamping instead of silently wrapping on overflow — an actual
// bounds check rather than a lint suppression, since these values do
// originate from caller-supplied config/arguments, not internal constants
// with a provably-safe range.
func pgInt32(n int) int32 {
	switch {
	case n > math.MaxInt32:
		return math.MaxInt32
	case n < math.MinInt32:
		return math.MinInt32
	default:
		return int32(n)
	}
}

// postgresSchemaSQL is internal/postgresdb/schema.sql, embedded so
// dlq.postgres.go's DLQHandler can apply it on connect without a separate
// migration tool — grpop has one linear schema, and CREATE TABLE IF NOT
// EXISTS is sufficient. The query code itself is generated by sqlc from the
// same directory (see internal/postgresdb) into its own internal package —
// standard Go practice for isolating generated code from hand-written code.
//
//go:embed internal/postgresdb/schema.sql
var postgresSchemaSQL string

// grpopSchemaLockKey is a fixed Postgres advisory-lock key used by
// applyPostgresSchema to serialize schema application across concurrent
// callers — e.g. multiple service replicas racing on first boot against a
// fresh database, where concurrent CREATE TABLE/INDEX IF NOT EXISTS
// statements are not fully race-free in Postgres. Advisory locks are global
// to the database, not namespaced per application, so an unrelated app
// that happens to choose this same int64 key could in principle collide
// with it — an accepted, extremely unlikely risk, not worth a namespacing
// scheme for a single fixed lock. Deliberately a different value from
// grnoti's own grnotiSchemaLockKey, since both modules may share a
// database in a consuming app.
const grpopSchemaLockKey int64 = 8_041_622_907

// PostgresConfig is the connection configuration for the Postgres-backed
// DLQHandler.
type PostgresConfig struct {
	// DSN is a standard libpq/pgx connection string. Exactly one of DSN
	// or Pool must be set.
	DSN string
	// Pool, if set, is used directly instead of dialing a new pool from
	// DSN — lets multiple grpop/grnoti/other-sibling Postgres stores share
	// one pgxpool.Pool instead of each opening its own. grpop never closes
	// a Pool it did not create itself: Close only closes the pool when it
	// was dialed from DSN. Exactly one of DSN or Pool must be set.
	Pool *pgxpool.Pool
	// MaxConns caps the pgxpool connection pool size. 0 means use pgxpool's
	// own default. Ignored when Pool is set — tune the pool yourself
	// before passing it in.
	MaxConns int32
	// MinConns keeps at least this many connections open. 0 means use
	// pgxpool's own default. Ignored when Pool is set.
	MinConns int32
	// MaxConnLifetime bounds how long a pooled connection may be reused
	// before being recycled. 0 means pgxpool's own default (unlimited).
	// Ignored when Pool is set.
	MaxConnLifetime time.Duration
	// ConnectTimeout bounds dialing and the initial Ping when connecting
	// from DSN. 0 means 10 seconds. Ignored when Pool is set (the Ping
	// against an already-established Pool uses the 10-second default
	// unconditionally).
	ConnectTimeout time.Duration
	// SkipSchemaEnsure, if true, skips applying grpop's embedded schema on
	// this connect call — for teams that manage the schema through their
	// own migration pipeline instead of grpop's built-in CREATE TABLE IF
	// NOT EXISTS.
	SkipSchemaEnsure bool
	// Logger receives optional diagnostic messages. A nil Logger disables
	// logging.
	Logger Logger
}

// connectPostgres resolves cfg to a pgxpool.Pool — either dialing a new one
// from cfg.DSN or reusing cfg.Pool directly — validates connectivity via
// Ping, applies the embedded schema unless cfg.SkipSchemaEnsure, and
// returns whether the pool is owned by this call: true only when dialed
// from DSN here, false when cfg.Pool was supplied externally, since an
// externally-supplied pool is never grpop's to close.
func connectPostgres(ctx context.Context, cfg PostgresConfig, component string) (*pgxpool.Pool, *postgresdb.Queries, bool, error) {
	if (cfg.DSN == "") == (cfg.Pool == nil) {
		return nil, nil, false, fmt.Errorf("grpop/postgres: exactly one of DSN or Pool is required for %s", component)
	}

	if cfg.Pool != nil {
		pingCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
		defer cancel()
		if err := cfg.Pool.Ping(pingCtx); err != nil {
			return nil, nil, false, fmt.Errorf("grpop/postgres: ping: %w", errors.Join(err, ErrBackendUnavailable))
		}
		if !cfg.SkipSchemaEnsure {
			if err := applyPostgresSchema(ctx, cfg.Pool); err != nil {
				return nil, nil, false, fmt.Errorf("grpop/postgres: apply schema: %w", err)
			}
		}
		return cfg.Pool, postgresdb.New(cfg.Pool), false, nil
	}

	poolCfg, err := pgxpool.ParseConfig(cfg.DSN)
	if err != nil {
		return nil, nil, false, fmt.Errorf("grpop/postgres: parse DSN: %w", err)
	}
	if cfg.MaxConns > 0 {
		poolCfg.MaxConns = cfg.MaxConns
	}
	if cfg.MinConns > 0 {
		poolCfg.MinConns = cfg.MinConns
	}
	if cfg.MaxConnLifetime > 0 {
		poolCfg.MaxConnLifetime = cfg.MaxConnLifetime
	}

	timeout := cfg.ConnectTimeout
	if timeout <= 0 {
		timeout = 10 * time.Second
	}
	connectCtx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	pool, err := pgxpool.NewWithConfig(connectCtx, poolCfg)
	if err != nil {
		return nil, nil, false, fmt.Errorf("grpop/postgres: connect: %w", errors.Join(err, ErrBackendUnavailable))
	}
	if err := pool.Ping(connectCtx); err != nil {
		pool.Close()
		return nil, nil, false, fmt.Errorf("grpop/postgres: ping: %w", errors.Join(err, ErrBackendUnavailable))
	}
	if !cfg.SkipSchemaEnsure {
		if err := applyPostgresSchema(connectCtx, pool); err != nil {
			pool.Close()
			return nil, nil, false, fmt.Errorf("grpop/postgres: apply schema: %w", err)
		}
	}

	return pool, postgresdb.New(pool), true, nil
}

// applyPostgresSchema applies the embedded schema (CREATE TABLE/INDEX IF
// NOT EXISTS) against pool, serialized by a Postgres session-level advisory
// lock (grpopSchemaLockKey) so concurrent callers apply it one at a time
// instead of racing on catalog DDL. The lock/exec/unlock sequence runs on a
// single acquired connection, since advisory locks are session-scoped, and
// is unlocked explicitly before the connection is released back to the
// pool — a released pooled connection is reused, not reset, so the lock
// would otherwise leak onto whichever caller acquires that connection next.
func applyPostgresSchema(ctx context.Context, pool *pgxpool.Pool) error {
	conn, err := pool.Acquire(ctx)
	if err != nil {
		return fmt.Errorf("acquire connection: %w", err)
	}
	defer conn.Release()

	if _, err := conn.Exec(ctx, "SELECT pg_advisory_lock($1)", grpopSchemaLockKey); err != nil {
		return fmt.Errorf("acquire schema lock: %w", err)
	}
	defer func() {
		_, _ = conn.Exec(ctx, "SELECT pg_advisory_unlock($1)", grpopSchemaLockKey)
	}()

	if _, err := conn.Exec(ctx, postgresSchemaSQL); err != nil {
		return err
	}
	return nil
}
