// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GrpopDlq struct {
	SendID         string             `db:"send_id" json:"send_id"`
	Channel        string             `db:"channel" json:"channel"`
	MessageData    []byte             `db:"message_data" json:"message_data"`
	FailureReason  string             `db:"failure_reason" json:"failure_reason"`
	RetryCount     int32              `db:"retry_count" json:"retry_count"`
	MaxRetries     int32              `db:"max_retries" json:"max_retries"`
	FirstFailureAt pgtype.Timestamptz `db:"first_failure_at" json:"first_failure_at"`
	LastAttemptAt  pgtype.Timestamptz `db:"last_attempt_at" json:"last_attempt_at"`
	NextRetryAt    pgtype.Timestamptz `db:"next_retry_at" json:"next_retry_at"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Status         string             `db:"status" json:"status"`
	AttemptHistory []byte             `db:"attempt_history" json:"attempt_history"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
