// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgresdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Step 2 of ClaimRetryableEvents: single-statement atomic claim, extended
	// with "AND expires_at > $1" so a row can never be claimed for retry past
	// its own deadline — this predicate is what actually enforces the cutoff;
	// step 1 above only exists so an event nobody claims in time still
	// surfaces as 'expired' instead of sitting silently in 'pending' forever.
	// The inner SELECT ... FOR UPDATE SKIP LOCKED lets N concurrent callers
	// each lock a disjoint set of candidate rows without blocking each other.
	ClaimRetryableEvents(ctx context.Context, arg ClaimRetryableEventsParams) ([]GrpopDlq, error)
	// Step 1 of ClaimRetryableEvents: proactively transition any Pending row
	// whose deadline has already passed to 'expired', regardless of whether
	// this call's own claim step (below) would otherwise reach it. Plain
	// UPDATE, no FOR UPDATE SKIP LOCKED — multiple replicas running this
	// concurrently is redundant but harmless (each row transitions once; a
	// second attempt on an already-'expired' row matches zero rows), so no
	// cross-replica coordination is needed here the way it is for the claim
	// step below.
	ExpirePastDeadlineEvents(ctx context.Context, arg ExpirePastDeadlineEventsParams) error
	// Step 2 of MarkRetried when the event goes back to pending (a retryable
	// failure, retries not yet exhausted and not yet past expires_at). See
	// UpsertDLQEvent's doc comment for the attempt_history cap subquery.
	FinalizeRetryPending(ctx context.Context, arg FinalizeRetryPendingParams) error
	// Step 2 of MarkRetried when the event reaches a terminal state: resolved
	// (success), exhausted (MaxRetries reached), or expired (recomputed
	// NextRetryAt would land at or past ExpiresAt — checked before the
	// MaxRetries case by the caller, see DLQHandler's doc comment). See
	// UpsertDLQEvent's doc comment for the attempt_history cap subquery.
	FinalizeRetryTerminal(ctx context.Context, arg FinalizeRetryTerminalParams) error
	GetDLQEventByID(ctx context.Context, sendID string) (GrpopDlq, error)
	// Step 1 of MarkRetried: atomically increment retry_count, scoped to the
	// claimed ("retrying") state — the WHERE clause is what makes this safe.
	// Returns no row if send_id doesn't exist or isn't currently claimed; the
	// caller distinguishes those two cases via a follow-up GetDLQEventByID.
	IncrementRetryCount(ctx context.Context, arg IncrementRetryCountParams) (GrpopDlq, error)
	// "Expired" here means grnoti/grpop's ORIGINAL sense (old enough to
	// delete), which predates and is unrelated to this table's own
	// DLQStatusExpired status — despite the shared word, they mean different
	// things (see DLQHandler.PurgeExpiredEvents' doc comment in interfaces.go).
	// This deletes every row in a terminal status (resolved/exhausted/expired)
	// OR any row older than $1, regardless of status.
	PurgeExpiredEvents(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	// File: internal/postgresdb/queries/dlq.sql
	// A single atomic upsert handles both "new failure" (insert) and "another
	// failure for a send_id already pending/retrying" (update, appending onto
	// the existing history) in one write path. The attempt_history assignment
	// caps the concatenated array to at most $11 entries, keeping the most
	// recent ones (oldest dropped first) — see the identical cap applied in
	// FinalizeRetryPending/FinalizeRetryTerminal below; all three share this
	// exact subquery shape so a pathological repeatedly-failing send_id can't
	// grow attempt_history without bound.
	UpsertDLQEvent(ctx context.Context, arg UpsertDLQEventParams) error
}

var _ Querier = (*Queries)(nil)
